# 1. Use the latest Ubuntu base image
FROM ubuntu:latest

# 2. Update the package list
RUN apt-get update

# 3. Upgrade installed software
RUN apt-get upgrade -y

# 4. Set the command to echo "Hello, World!" when the container starts
CMD ["echo", "Hello, World!"]
